### ISSUE TITLE
Synthesis Patcher Q&A

### ISSUE THREAD

**Issue by SteveTownsend** [SlavicPotato/ied-dev#1]
I thought I'd open this to take the discussion off Nexus if that's OK? [RESOLVED The sample meshes in vanilla do have hidden flag on _ScbLeft_ but I don't see that _ScbLeft_ mirrors _Scb_ in either case - am I misunderstanding?]

I don't think this will be very hard - there is already block-mirroring logic for the AllGUD alternate meshes. I'm just going to get it done, forget about the Github repo refactoring for now.

**Comment by SteveTownsend** [comment]
OK I dug into it a bit, I think I see what is going on. The existing Mirror block logic flips along X axis but doing along Z is a two-line change

**Comment by SlavicPotato** [comment]
Yeah it should only be mirrored on Z. The iron mesh (modified) with its long strap is a pretty good example:

![.](https://i.imgur.com/NWxrefm.png)

**Comment by SteveTownsend** [comment]
This logic is only going to apply for 1H weapons, correct? e.g. I don't want to mirror if some mod adds greatsword scabbards

**Comment by SteveTownsend** [comment]
Initial mesh output, needs to be properly checked though
![image](https://user-images.githubusercontent.com/14825099/150139992-55fda23d-7dfa-4551-999b-b9d9a4bab6da.png)

**Comment by SteveTownsend** [comment]
There is extra logic in AllGUD block mirroring to apply any transform in the original mesh during the mirroring process. I wonder if this is needed for the scabbard block mirroring? I've left it in for now, easy to strip if this looks wrong.

**Comment by SteveTownsend** [comment]
The patcher runs OK for me. My big q is whether or not apply-transform is needed, or just the simple mirroring. I am following AllGUD script logic for block mirroring, but maybe scabbard is a special case.

**Comment by SlavicPotato** [comment]
> This logic is only going to apply for 1H weapons, correct? e.g. I don't want to mirror if some mod adds greatsword scabbards

Pretty much, yeah. There is CGO with its 2H dual equip thing, but we shouldn't bother with that.

> There is extra logic in AllGUD block mirroring to apply any transform in the original mesh during the mirroring process. I wonder if this is needed for the scabbard block mirroring? 

I could be missing something but I'm pretty sure that's a no. Atleast I didn't have to in the dozens of meshes I converted by hand. 

I'll check out the patcher in a bit!

**Comment by SteveTownsend** [comment]
OK let me back out the transform logic first, that's a one liner. Thanks
for trying this out. If you've used my AllGUD one it works like that  but
way simpler to set up - default input folder should be fine, define output
folder to be your new mod location (just meshes)

**Comment by SteveTownsend** [comment]
done, you should be good to try this when you have the time.

**Comment by SteveTownsend** [comment]
> if it could somehow orientate from the geometry center instead of the node it should correct this

This seems like an extra credit project. I'll release the baseline with these outliers uncorrected, I think.

> first person meshes should be processed too if present (WNAM records pointing to STAT)

Do you have an example of this please? The referenced STAT formid is enough

**Comment by SlavicPotato** [comment]
Ebony sword points to: 1stPersonEbonySword [STAT:00036BDF]

The mesh layouts are typically identical, 1p model geometry is usually more detailed (higher vertex count)

**Comment by SteveTownsend** [comment]
Yeah I found them in SSEEdit - thanks. I'll add logic to pull up those NIFs into the list to decorate

**Comment by SteveTownsend** [comment]
OK this is up there, it adds quite a few!

**Comment by SteveTownsend** [comment]
Closing this for now - feel free to reference the patcher where the mod page talks about manual scabbard fixup. I doubt I'll add a mod page for this, I can't be bothered to build the standalone patcher EXE - people should just use it inside of Synthesis. Thanks for your help getting it up and running.

**Comment by SlavicPotato** [comment]
Will do and thank you, this thing is awesome. I wasn't too bothered by the manual patching but this improves the QoL a lot. If you do put it on nexus let me know and I'll link it on SDT and IED.

**Comment by SteveTownsend** [comment]
sure thing, this is minor work compared to IED which is a stupendous
achievement
