### ISSUE TITLE
set hotkey to num, and ui became permanently inaccessible even after reinstalling AND redownloading

### ISSUE THREAD

**Issue by PoroUnited** [SlavicPotato/ied-dev#12]
oke so bug report unable to access ui anymore. not after reinstalling not after redownloading not after anything so far.

steps to "reproduce" is not testable since as my bug states it cant be undone (or at least i dont know how).
the steps are: setting the hotkey to numlock comma.... a non exciting key i though it was supposed to be a period but its now officially as far as im aware inaccessible no matter what i do.

game version AE

my modlist is irrelevant and there is no crash so no report

**Comment by SlavicPotato** [comment]
See ```ToggleKeys``` and ```OverrideToggleKeys``` in the ini.
