### ISSUE TITLE
CTD when loading presets

### ISSUE THREAD

**Issue by sl3y551** [SlavicPotato/ied-dev#13]
Hello, im playing on a heavily modded list and im not quite sure what is causing this. My game will crash whenever i merge/apply a preset. Im aware its most likely a "me" problem but i would like some experts opinion what could cause this, since its related to IED. Here is my crashlog, i had to upload it cause its too many characters.

Edit: I should clarify what exactly happens, so for example i installed Missile's preset and they are split up into multiple ones for different things. I merge one and it works fine, then if i will merge the next one it would crash. One time it crashed after merging all presets, but then i unequipped my chest armor and the ctd happened.

[Crash_2022_7_21_20-58-44.txt](https://github.com/SlavicPotato/ied-dev/files/9162060/Crash_2022_7_21_20-58-44.txt)

**Comment by SlavicPotato** [comment]
Seems like a bad mesh, most likely missile\clutter\TorchHolder.nif that seems to be sourced from FEXXX806 (Missile IED Meshes.esp).

Apparently a broken collision mesh, it crashes while the game is cloning it.
