### ISSUE TITLE
Condition for in combat

### ISSUE THREAD

**Issue by Torllay** [SlavicPotato/ied-dev#14]
How could I make a rule that when I am not in combat my shield is on my left hand but if I pull out a two-handed weapon it goes on my back? I can't find a condition for this.
I needed it specifically for when I'm in combat as I tried for equipped weapons, but as I'm playing mainly 2H lately it would always be on my back.

**Comment by SlavicPotato** [comment]
Combat condition was added in 3d42484252655f2ff3a6f7597b4eee02722e44c4, it's not on nexus yet.

**Comment by Torllay** [comment]
First of all, thank you for the answer.
What will the name be of the condition and under which category?
Also, where can i get that version? Maybe a Patreon or here?

**Comment by SlavicPotato** [comment]
Only when you're in combat, a separate condition for weapon draw state was just added in 79fbbb54f60a2ebf7fc583302b4c0b08723056c3

Still needs testing, idk when it'll be on nexus

**Comment by Torllay** [comment]
I will keep waiting impatiently, thank you for your work! <3
