### ISSUE TITLE
New condition of Active/Magic effect

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#15]
Hi.
Suggesting a new condition for Active/Magic Effect present on the actor.
Various mods add animations or other stuff via spells or potions that deliver a magic effect to the Player/NPC, so I think this could be useful.

Edit (new request): Item filter for allow/deny forms (in Equipment slots) it's pretty neat, but is it possible to implement keywords(that are present in the forms) too?

Also a minor visual bug that bothered me a bit (sorry):
Adding a condition for a group inside a group creates a visual bug on the grid, it goes away by fully expanding the window.
Images for reference, [here](https://i.imgur.com/TiqDcWr.png) and [here](https://i.imgur.com/gHetmRS.png).

Ps. Couldn't find an option to tag this as a feature.

**Comment by SlavicPotato** [comment]
> Adding a condition for a group inside a group creates a visual bug on the grid, it goes away by fully expanding the window.

Beyond a certain depth it's necessary to add horizontal scrollbars to ensure that controls are reachable when there's no more available content area width, unfortunately this also disables table height expanding to content size so a fixed height needs to be set and vertical scrollbars turned on. Maybe there's a better approach, for now this stopgap measure will have to do.

**Comment by SlavicPotato** [comment]
I think that should do it. Active effect lists on actors are scanned for changes only every 0.33 secs to save some cpu time. I can upload a preview build if you want to test, lmk.

**Comment by GiraPomba** [comment]
> Beyond a certain depth it's necessary to add horizontal scrollbars to ensure that controls are reachable when there's no more available content area width, unfortunately this also disables table height expanding to content size so a fixed height needs to be set and vertical scrollbars turned on. Maybe there's a better approach, for now this stopgap measure will have to do.

No worries, that was nitpicking on my part.

> I think that should do it. Active effect lists on actors are scanned for changes only every 0.33 secs to save some cpu time. I can upload a preview build if you want to test, lmk.

That was fast. 
Sure, I can test it.

**Comment by SlavicPotato** [comment]
It was a simple change, just needs to be tested. Keyword filters might be a bit more work, I'll look into it later.

[Uploaded](https://github.com/SlavicPotato/ied-dev/releases/tag/1.7.0a). There's also built-in equipment physics and actor variables that you might want to try out. Form variables in particular may be of some interest, you can set them to last-equipped forms on one actor then use them in custom items on another, a horse for example. I didn't include a sample preset but if you're interested I can upload it separately.

**Comment by GiraPomba** [comment]
Wow, some pretty cool features, I'll definetely check them.
No need for presets I think, but I'll let you know.

**Comment by SlavicPotato** [comment]
A simple setup it's relatively easy but to manage available gear you'd need to use the presence condition. It tests for the availability of the item being processed, accounting for equiped/displayed state, inventory count and how many times it was consumed by other variables. Since I'm too lazy to go into detail rn, see attached samples below if you're interested in the feature. 
[vars-example.zip](https://github.com/SlavicPotato/ied-dev/files/10106053/vars-example.zip)

**Comment by GiraPomba** [comment]
Testing those Form Variables, it's awesome. A bit tricky to set up but I think I got the hang of it.

I can 99% say for sure that it made my mod that uses scripts to achieve something similar (player gear on horse) obsolete. Actually I'm not even mad, that's amazing.

Will test the Magic Effect now and let you now.

**Comment by SlavicPotato** [comment]
> Edit1: Is there a way to combo form vars with "Inventory Item" and "Additional Items"? Currently I'm creating a var for each form and using this workaround to check if it's in the player inventory. Image [here](https://i.imgur.com/f9L0wnu.png) (Should be Count>0, but yeah....)

The condition approach you're using is fine, same thing as inventory mode. Additional forms wouldn't make sense here, but you can list multiple variables in custom items, each will be considered (in order).
 
> Unrelated question about the video. As you can see, the paraglider display is stretching while moving down, I tried disabling the collisions and animations but it persisted, so I guess it's something unrelated, maybe the mesh? Is there something that could be done in IED to prevent this?

The ground object was designed that way, it has lag bone controllers on nodes attached around the parasail (see paraglider_gnd.nif) to add some basic of animation. You can edit the values on BSLagBoneController objects in the mesh (velocity, rotation, max. distance, ..) to adjust this. IED can't control this stuff and doesn't affect it, you'd see the same thing throwing it off a cliff (assuming it reached the same velocity).

> Edit3: About the projectiles displays, if it's not asking too much, could you add a option to remove the "tracing"? And could you make it accessible through the script's functions too?

Shouldn't be a problem but I need to check the meshes.

About keyword filters, I was thinking of adding filter conditions for equipment candidates instead, like last-equipped mode has. It'd be way more powerful and would be way simpler to add unlike a keyword filter that would have to be implemented basically from scratch.

Btw github won't send me notifications for post edits, I'd probably never see them if I didn't come here to suggest filter conditions. Feel free to just make as many separate comments as needed.

**Comment by GiraPomba** [comment]
> The condition approach you're using is fine, same thing as inventory mode. Additional forms wouldn't make sense here, but you can list multiple variables in custom items, each will be considered (in order).

Right, I was trying to create a display to show dragon claws in the player's inventory on the horse, but I wanted to display only the first dragon claw found. So, the additional items would be handy here, but I'll make additional vars then.

> The ground object was designed that way, it has lag bone controllers on nodes attached around the parasail (see paraglider_gnd.nif) to add some basic of animation. You can edit the values on BSLagBoneController objects in the mesh (velocity, rotation, max. distance, ..) to adjust this. IED can't control this stuff and doesn't affect it, you'd see the same thing throwing it off a cliff (assuming it reached the same velocity).

Thanks for looking into it and showing me where to edit this.

> About keyword filters, I was thinking of adding filter conditions for equipment candidates instead, like last-equipped mode has. It'd be way more powerful and would be way simpler to add unlike a keyword filter that would have to be implemented basically from scratch.

Yeah, that sounds nice, It will be more dynamic too, thanks.

> Btw github won't send me notifications for post edits, I'd probably never see them if I didn't come here to suggest filter conditions. Feel free to just make as many separate comments as needed (better yet, open a new issue for each feature request) .

Oh, I see. I assumed you haven't read this yet as I didn't want to clutter this thread with more messages. 
I can open new issues if you want though.

**Comment by SlavicPotato** [comment]
> I can open new issues if you want though.

Yeah go for it, it's easier to track and discuss separate issues as opposed to jamming everything in to a single one. Plus when I add a commit I can reference a particular issue.
