### ISSUE TITLE
New options to filter forms in Equipment slots

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#16]
There is this option to filter for specific forms to allow or deny in the equipment displays.
Suggesting new options for it. The original suggestion was to use Keywords.

**Comment by GiraPomba** [comment]
Hey. Just wondering.
Could this system for filtering items be implemented in the custom displays, along the Last equipped option?
I was trying to make a display for player crafted potions and I couldn't make a link with the potions in the inventory, afaik the form ids are created in the savefile.

**Comment by SlavicPotato** [comment]
There already is a condition filter for last equipped, but temporary forms are ignored in general. They can be deleted at any point, their ids assigned to another form - too risky and problematic to deal with. It won't let you display temp forms or detect them in inventory (maybe this last part could be changed at some point)
