### ISSUE TITLE
Option to disable/enable "tracing" for projectile displays

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#17]
The game already does something to remove the "tracing" when the projectiles are laying around, by firing from a weapon or dropping individually from the inventory.
Suggest making this acessible through the script's functions too.

**Comment by SlavicPotato** [comment]
I think that should do it, only did a very basic test though. New test build is up.

**Comment by GiraPomba** [comment]
Hey, 
Just tested and it's working perfectly, the script function as well.
Thanks a lot.
