### ISSUE TITLE
Question about Is Weapon Drawn condition

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#18]
Hi. 
The condition works fine, but I was wondering if it could be changed.
I was setting a display to be disabled when a weapon was drawn; as soon as the weapon was drawn the display was disabled, as expected.
When the weapon was sheathed, the display was enabled back, but it happened at the start of the sheathing animation and not at the end.
I guess the function evaluates at sheathe begin then. Is it possible to evaluate at sheathe end?

**Comment by SlavicPotato** [comment]
This is actually due to a mistake I made in the libs and it affects simple dual sheath too. I'll upload a new SDS build to nexus in a bit and IED test build here too.

**Comment by SlavicPotato** [comment]
Nexus file management is taking a dump right now so the files may or may not be available. Anyhow, thanks! I'll get those IED test builds up in a bit.

**Comment by GiraPomba** [comment]
:) 
Just reporting that it worked perfectly, thanks.
