### ISSUE TITLE
Effect condition with Inactive effects

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#19]
Hey, a bit late perhaps. 
But I tested the new condition more extensively today and I noticed that if the effect is present for the actor but it's currently "Inactive" the condition still validates as True.
Could you change it to validate as false in this case?

**Comment by SlavicPotato** [comment]
Should be fixed in the preview build.

**Comment by SlavicPotato** [comment]
Just a heads up: there was a mistake in the last pre-release, I've just pushed a new one.

**Comment by GiraPomba** [comment]
Thanks, new version is awesome.
