### ISSUE TITLE
String encoding format for UTF-8 characters (Chinese, Korean Japanese etc)

### ISSUE THREAD

**Issue by Kepler-16b** [SlavicPotato/ied-dev#2]
Json file does not like those characters, so what is the correct way to translate UI?

**Comment by Kepler-16b** [comment]
Also all NPC names are not displayed correctly in config menu. Will UTF-8 character support be added?

**Comment by SlavicPotato** [comment]
The file must be utf-8 encoded and unicode glyph ranges for the language must be defined in it. If you're not sure how to do that you can send me the file after you've translated it and I'll add those. 

I've just push a commit for that, it will be added in the next version.
