### ISSUE TITLE
Condition by Type>Torch

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#20]
Hi, I'm trying to condition a display to be disabled when a torch is equipped, but I'm failing to do so,

I tried with Type>Torch, but the condition doesn't seem to validate with "Equipped" ticked.
However, it does disable the display when all options are unticked and when a torch is present in the inventory.

Maybe I'm misunderstanding the Type>Torch condition.

**Comment by SlavicPotato** [comment]
> Maybe I'm misunderstanding the Type>Torch condition.

Nah, it wasn't detecting equipped torches at all. Should be fixed now, I'll upload new builds in a bit.

**Comment by GiraPomba** [comment]
Working now, thanks!!
