### ISSUE TITLE
Crash on 1.6.3

### ISSUE THREAD

**Issue by zhongjiedong** [SlavicPotato/ied-dev#21]
Using Skyrim SE 1.5.97. CTD randomly, sometimes on load.

crash log attached
[Crash_2022_12_17_14-51-25.txt](https://github.com/SlavicPotato/ied-dev/files/10251959/Crash_2022_12_17_14-51-25.txt)

Disabling IED removes crashing

**Comment by SlavicPotato** [comment]
Nothing in the crashlog directly points to IED. It's most likely something specific in your load order combined with the mod that's causing it. Not much I can help your with unfortunately.

**Comment by zhongjiedong** [comment]
thanks will give it a go :)
