### ISSUE TITLE
Recurring CTD

### ISSUE THREAD

**Issue by allison-payne** [SlavicPotato/ied-dev#26]
I have a recurring CTD with this dll in the list. I am not convinced it is your mod, as skeletons can be weird. If you have some time to look into the attached crash log, and point me in a direction, I would be very grateful.
[Crash_2022_12_25_1-19-44.txt](https://github.com/SlavicPotato/ied-dev/files/10300555/Crash_2022_12_25_1-19-44.txt)

**Comment by SlavicPotato** [comment]
> I am not convinced it is your mod, as skeletons can be weird.

There's not even a trace of evidence pointing to this mod in the log you've attached. You've got > 150 dlls (I see atleast one with known issues) and 1500 beth plugins crammed together, if it doesn't crash every 30 mins it's a miracle. If you do have an issue with this mod and provide atleast some evidence I'll gladly take a look, but please don't (ab)use gh issues for personal LO tech support.
