### ISSUE TITLE
crash when turn from vampire lord into human back

### ISSUE THREAD

**Issue by chumik6000** [SlavicPotato/ied-dev#27]
I get a crush when turn from vampire lord into human back, can u fix this? 
https://drive.google.com/file/d/14PCXvM-suHbcIUyx9u6QK-XIRSOuTHv2/view?usp=sharing
Alsow i have partical light effect when tourch on my belt.

**Comment by SlavicPotato** [comment]
Won't fix your random crashes, it's not caused by this plugin
