### ISSUE TITLE
CTD with Fall back to equipment display slot

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#31]
When selecting this option in a custom display, the game CTD.
It seems to only happen with some specific presets. I don't know exactly what is different on these presets, so maybe it's something in the .json file itself.

How to reproduce:
Load the preset below and apply it in custom view.
Click on the option "Fall back to equipment display slot"

Preset: [https://pastebin.com/cqmJZuuL](https://pastebin.com/cqmJZuuL)
Crash log: [https://pastebin.com/f4HbtnYT](https://pastebin.com/f4HbtnYT)

I hope you don't mind that I uploaded the preset in pastebin, I can send through another way if needed.

Some other stuff I noticed in the GUI:
[https://imgur.com/wy6y2FY](https://imgur.com/wy6y2FY)
[https://imgur.com/gTh11OX](https://imgur.com/gTh11OX)

**Comment by GiraPomba** [comment]
Unrelated question: Could you add Editor ID as a column in Form Browser?

**Comment by SlavicPotato** [comment]
Nice find. I'm curious, did add an invalid slot ID (19) to the list manually? Asking because it shouldn't normally happen.

> Unrelated question: Can you add Editor ID as a column in Form Browser?

Maybe, if it's not too expensive to look up and cache them for the FB. I'll have to check.

**Comment by SlavicPotato** [comment]
About pic2: disable collision was added to the base config, both custom and slots inherit from it so the option can now be used under slots too. The legacy option which is only available on custom displays was left there for backwards compatibility. Both do the same thing.

**Comment by GiraPomba** [comment]
> Maybe, if it's not too expensive to look up and cache them for the FB. I'll have to check.

Okay, could be useful with forms that you can't normally add a name.

> About pic2: disable collision was added to the base config, both custom and slots inherit from it so the option can now be used under slots too. The legacy option which is only available on custom displays was left there for backwards compatibility. Both do the same thing.

Gotcha. It was there for some time already, but I was just wondering.


Some questions if you don't mind answering:
How does the "Remove scabbard" function works; Does it looks the mesh from the "scb" block and then remove it on the fly?
Could be possible to add a reverse of that? Like, remove everything else but keep the "scb". Sounds niche I know, but I use some displays for weapons in custom view and it would be nice to have scabbard in place when they're disable during certain conditions. I could also create new meshes for that.

How does the "In dark area" function works? I didn't find it in the wiki.

**Comment by SlavicPotato** [comment]
> How does the "Remove scabbard" function works; Does it looks the mesh from the "scb" block and then remove it on the fly?

Yeah, same way the game does it.

> Could be possible to add a reverse of that? Like, remove everything else but keep the "scb". Sounds niche I know, but I use some displays for weapons in custom view and it would be nice to have scabbard in place when they're disable during certain conditions.

An option to hide the weapon independently of the scabbard could be added fairly easily. That way, the model wouldn't have to be reloaded when the override takes effect.

> How does the "In dark area" function works? I didn't find it in the wiki.

[Added it](https://github.com/SlavicPotato/ied-dev/wiki/Conditions#in-dark-area)

**Comment by GiraPomba** [comment]
That would be great. Thanks.

**Comment by SlavicPotato** [comment]
New build is up, the option we talked about is under Model->Geometry.

**Comment by GiraPomba** [comment]
> New build is up, the option we talked about is under Model->Geometry.

That was fast and worked perfectly. Thanks a lot.

About the Fall back option: 
CTD is gone, but It's creating an empty line now on those presets when enabling, I don't think it will cause any issues, unless it tries to filter by it.
[https://imgur.com/qEEy8wV](https://imgur.com/qEEy8wV)

In any case, it's possible to delete the line.

**Comment by SlavicPotato** [comment]
Entries with invalid ids were created in any preset that fell victim to the faulty version transition during import. 646eb03 addresses this so it shouldn't happen again. Invalid entries are ignored by the gear system so it shouldn't cause problems but I recommend cleaning them nontheless to keep things tidy.
