### ISSUE TITLE
Number of "states" for keybinds

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#39]
Maybe a wild idea (lol). But what if the keybinds had more than two "states"?
User could configure the max number of states of the key, each press would increase the state by one, reverting back to 0 when the limit is reached.

Possible use:
A certain display with two overrides:
One override to be enabled in certain conditions.
Another override to be disabled in certain conditions.

Adding the keybind to the two conditions(or in new ones) using more than one state:
State == 1, means display is enabled disregarding the other conditions.
State == 2, means display is disabled disregarding the other conditions.
State == 0. no conditions for this, meaning the other conditions would take effect.

**Comment by SlavicPotato** [comment]
Yeah it occured to me too that multiple states might be useful, just the other day. It's a minor change, but it won't be backwards compatible, you'll need to go though any key bind conditions you have and set the comparison operator and state manually.

**Comment by GiraPomba** [comment]
Tested new version and it's working fine. Closing this, there's an option to save, so no need for preset editor I think.

**Comment by SlavicPotato** [comment]
Binds are stored in a config file on disk right now (combo & key), just the current states are serialized in the cosave. This is kinda weird now since multiple states were added. I think it would be better if everything was stored in the cosave and a preset system added.

**Comment by GiraPomba** [comment]
So, loading a config wouldn't set the states if not present in that particulary save. Yeah, maybe a preset would be better indeed...

**Comment by SlavicPotato** [comment]
Bind config is in the cosave now, any binds you had stored in the old config will need to be re-created. Let me know if there are any issues.

**Comment by GiraPomba** [comment]
Hey, did some tests today and it's working perfectly so far.

**Comment by GiraPomba** [comment]
A question about hotkeys, but for the settings keybinds(open UI).
Can ImGui detect when another ImGui or other similar menu is open? I was editing a value in another mod's UI and pressed backspace and it opened IED, maybe it could be blocked in this case if possible. I could just add a combo key too in any case.

**Comment by SlavicPotato** [comment]
ImGui can't detect anything, it's a simple low-level library that draws stuff on your screen through the render pipeline. There's no standardized way of processing IO in skyrim and very little coordination between mods, it's the user's responsibility to configure keybinds so that they don't overlap. I don't know of any mod that doesn't allow you to do this so it's a non-issue.
