### ISSUE TITLE
ImmersiveEquipmentGenMesh

### ISSUE THREAD

**Issue by Bvckshot** [SlavicPotato/ied-dev#4]
Hi, Im having trouble getting the ImmersiveEquipmentGenMesh patcher to work through Synthesis. Im running the patcher and not seeing any errors, copying the mesh folders, the ESP, and the Data folders that are generated by Synthesis, but I dont see any changing result in game. I use MO2 and would appreciate any feedback. If i need to provide any logs I will also do so, thanks!

**Comment by SlavicPotato** [comment]
Refer questions about the patcher to its project page.
