### ISSUE TITLE
Assertion Failed in IED\SkeletonCache

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#41]
This error happens when the "Sync first person gear nodes", under Settings, is toggled.
[https://i.imgur.com/9jMEGjI](https://i.imgur.com/9jMEGjI.png)

Skyrim Version 1.6.353. latest preview version.
No crash logs.

**Comment by SlavicPotato** [comment]
Should be handled now, grab RC12.

How is it performing with the background loader? Noticed anything weird?

**Comment by GiraPomba** [comment]
Not that I noticed, but I didn't have much time to play the game. 
Though I did notice that the stutters where gone, I had some when loading new meshes with the presets or through the script functions. Now it's running pretty smooth.

Will do some more gameplays later.

**Comment by SlavicPotato** [comment]
Another thing I wasn't happy with was having to load texture swaps from the main thread, RC13 should take care of that. Options are in the ini, ```ObjectManager``` section.

**Comment by GiraPomba** [comment]
Alright, will test that too. Is it for items with same models but different texture sets or something else?

**Comment by SlavicPotato** [comment]
Yeah, that's it. Texture loads are very expensive, having to block the main loop while they load isn't great.

**Comment by GiraPomba** [comment]
I noticed that, at random, the displays take some time to load, between 0.5 to 1 second. Via scripts or the UI.

I haven't noticed this in previous version. But I might be wrong, I have a kind of a budget pc. Will do more tests later.

**Comment by SlavicPotato** [comment]
As long as it doesn't lock the game up while it's doing it, that's fine. It could any amount of time to load and process the mesh, depending on the quality, your pc, whether the game is loading in any other assets (ied tasks are set to low priority so loads have to wait in such cases), etc...

**Comment by SlavicPotato** [comment]
Another possible reason why loads might take longer is if item evals wouldn't fire promptly after load/clone operations, RC14 addresses some possible issues there. If you do still find long loads seemingly without reason, it's probably something with background cloning (confirm by turning it off in the ini).

**Comment by GiraPomba** [comment]
Yeah, did some tests without the cloning enabled and the displays were created immediately.
I will keep it available since it's not really an issue and it's more performance friendly.

**Comment by SlavicPotato** [comment]
0.5-1 sec is a bit high though, the background processor queue would shouldn't get that clogged. What settings were you testing with? "1" (default for player) bg clones only if there's a swap texture which is rare for non-armors. Asking for more info since there could actually be a problem somewhere.

**Comment by GiraPomba** [comment]
I don't think it was taking a full second to load a mesh. I created some displays to be enabled when some weapons were equipped and then kept cycling the weapons. The displays were enabled shortly after, some times a bit longer, some times almost immediately.

I was using default settings. I will do more tests later but I don't think it's an issue.
