### ISSUE TITLE
About Node Monitor condition

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#47]
Does the condition check for loaded AnimObjects on the actor or is it something different?
If it's the former, is it possible to add a field where you can search for any AnimObject?

**Comment by SlavicPotato** [comment]
It basically just looks for a particular node on the skeleton, doesn't care what that node is used for. `test` is the search mode (i'll add docs on this later), first bit of `flags` is recursive search.

**Comment by GiraPomba** [comment]
Okay, thanks.
So, right now it's hardcoded to check for Lutes, Drums, etc?
I have some animations with AnimObjects and it would be nice to make conditions based on them.

Speaking of nodes, can you tell me how to use the Two Handed Extra and Bow extra? I tried searching the forum tab, but couldn't find any info on this.

**Comment by SlavicPotato** [comment]
It isn't hardcoded, configs go in IED/NodeMonitor

**Comment by GiraPomba** [comment]
Right, should've looked first before asking lol..
It worked, thanks.

Loading multiple "subjects" would be too much to ask?
[https://i.imgur.com/CRX8HMG.png](https://i.imgur.com/CRX8HMG.png)

**Comment by SlavicPotato** [comment]
Define those in `additional_subjects` member (type is array)

**Comment by SlavicPotato** [comment]
Nope, it was added around 2 months back

**Comment by GiraPomba** [comment]
Nice, I think I'll wait a bit then.

**Comment by SlavicPotato** [comment]
What was the mod and which mesh file?

Just pick a random, high number, avoid 0-1000 since I may use these ranges in default configs

**Comment by GiraPomba** [comment]
Alright. 

Mod: [Animated Potions](https://www.nexusmods.com/skyrimspecialedition/mods/73819) 
Mesh: Meshes\AnimObjects\potionhealthlesser.nif

**Comment by SlavicPotato** [comment]
You could do a recursive search for ```PotionHealthLesser:0```, set the first bit of ```flags``` to 1

**Comment by GiraPomba** [comment]
Not sure what I'm doing wrong here, but I can't get it to work:
NodeMonitor .json:
[
	{
		"uid": 2000,
		"flags": 1,
		"test": 3,
		"desc": "Health potion anim object",
		"skeletons": 
		{
			"sigs": 
			[ 
				11462500511823126705, 
				2191670159909408727, 
				11827777347581811248, 
				6419035761879502692,
				271026958073932624,
				4625650181268377090,
				10927971447177431054,
				17428621824148309550
			]
		},
		"parent": "AnimObjectR",
		"subject": "PotionHealthLesser:0"
	}
]

Display:
[https://i.imgur.com/n2K4oei.png](https://i.imgur.com/n2K4oei.png)

**Comment by SlavicPotato** [comment]
set ```test``` to 2

**Comment by GiraPomba** [comment]
Didn't work :/

**Comment by SlavicPotato** [comment]
Recursive search doesn't seem borked neither does that test. Verify your nm entry on a custom object first, make sure it's correct before you use it in practice

**Comment by GiraPomba** [comment]
Alright. I'll do some more tests to see if I can figure what's going on. If nothing works, I'll end up renaming the BSFadeNodes and use `flags:0`.

Thanks for your help and answering my questions.
