### ISSUE TITLE
Question about Physics

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#48]
Hey, it's me with the questions again. 
So I finally managed to play around with the "Physics" feature of the mod, and it's pretty awesome so far, great implementation.
The Physics Debug renderer is a great help to visualize what I'm doing with the configs, otherwise I would have to waste a lot of time.

I'm using the included preset and it's pretty good, but I want to add some more jiggle or remove from some weapons. Do you mind telling what values does this? I guess it's something in the rotation scaling? I tried messing around but the weapons started behaving weirdly.

Speaking of the renderer, is it possible to implement something similar to the transform configs? Sometimes when creating a display for an item, changing the rotations axes don't go as I expect them to. Nothing wrong with IED in this regard, but I think it's how the mesh is made, it feels like it rotates the same way when changing two different axes. Maybe with a visual representation would help.

**Comment by SlavicPotato** [comment]
Hey,

you'll mainly want to play around with spring stiffness and constraints (make sure the node has plenty of room to move around, green ball in the dr), rotation scale is the magnitude of rotational movement. It's a very basic implementation (based on cbp), i'm not really happy with some aspects, for example linear motion directly translating to angular motion. On the upside, it's very cheap to run and heavily optimized (uses multiple cpus, simd instructions and shuts down simulation on nodes w/o 3D) so it barely makes a dent in frametimes (you can measure the avg delta time per frame in stats, actor processor, toggle physics in settings).

Re second question, lookup gimbal lock

**Comment by GiraPomba** [comment]
I think it's great, well I wouldn't know how to compare anyway haha. But the freedom to create configs with the UI, for different actors(I'm applying to horses) and for different conditions, it's already better than CBP imo, regarding equipment/displays anyway.

About the gimbal lock. Yeah, that makes sense, I didn't know about that. 
I guess I'll need to change the other axis to "unlock" then.

Thanks..

**Comment by SlavicPotato** [comment]
You get everything that cbp has + additional stuff like constraints with none of the weird framerate issues that cbp had (and i think cbpc has to this day), so a fairly stable simulation at variable framerates with substepping, delta-t averaging... It's good enough for equipment physics but when it comes to accurate simulation it still sucks ass same as cbp. I might add a more accurate implementation down the line when I get some free time

**Comment by GiraPomba** [comment]
That's awesome, looking forward to it.
