### ISSUE TITLE
Shield changes size when not equipped

### ISSUE THREAD

**Issue by zhongjiedong** [SlavicPotato/ied-dev#5]
see video: https://giant.gfycat.com/AmusingDependableCanvasback.mp4

This in combination with simple dual sheathe and xp32 skeleton with the fixed scripts

**Comment by zhongjiedong** [comment]
on closer inspection my fixed scripts were being overwritten by https://www.nexusmods.com/skyrimspecialedition/mods/60363

This might be the old xp32 issue where stuff would flicker and change size as this patch doesn't seem to include the fixed scripts

**Comment by SlavicPotato** [comment]
XP32 scales it when equipped to match the smaller female hand. Around 0.85 iirc. Just adjust it in the config, equipment view->shield so it affects just the display, do not use gear positioning.
