### ISSUE TITLE
Use Form Variable in Override model or Model swap for Custom/Equipment displays

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#51]
Hey, it's been a while. 
Not sure if you're still going to implement new stuff here, but I thought this should be an interesting addition.

What it says in the title, the possibility of using Form Variables in Override models or Model swaps. It'll be possible to significantly reduce Equipment override conditions if loading forms from a variable.

**Comment by SlavicPotato** [comment]
[ImmersiveEquipmentDisplays.zip](https://github.com/SlavicPotato/ied-dev/files/13762347/ImmersiveEquipmentDisplays.zip)
That should do it, I've attached a build if you care to test that it works properly. It's pre 1.6.629, lmk if you run a newer build atm

**Comment by GiraPomba** [comment]
Hey, that's neat.
I'm on v1.6.640 at the moment.

**Comment by SlavicPotato** [comment]
[Post 629 build](https://github.com/SlavicPotato/ied-dev/files/13762355/ImmersiveEquipmentDisplays.zip)

**Comment by GiraPomba** [comment]
Hey, works alright in Custom displays, but doesn't seem take effect in Equipment slots.

**Comment by SlavicPotato** [comment]
Wasn't enabled there, [here you go](https://github.com/SlavicPotato/ied-dev/files/13769891/ImmersiveEquipmentDisplays.zip)

**Comment by GiraPomba** [comment]
Seems to be working perfectly now. Thanks.
