### ISSUE TITLE
Request for new options in Gear nodes.

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#55]
No idea how doable this is, but I think this could be some neat addition.

In "Positions", under "Visibility", add a new option for "Remove scabbard" and a new option for "Hide geometry" (that option from Display manager that only keeps the scabbard).

If not, then maybe a way to use a node in Display manager when it's invisible in Gear nodes? Currently, the node is invisible as well.

**Comment by SlavicPotato** [comment]
When you hide a gear node, it only sets the hidden flag that CME node - anything attached below it automatically becomes invisible as a result but no child nodes are actually written to.

Gear nodes don't (and never will) touch anything below the CME node. Arbitrarily removing or even hiding parts of an item equipped by the game would break things.
