### ISSUE TITLE
torch when favorited even if not used/equipped will create a glow around the player

### ISSUE THREAD

**Issue by JoshStLee** [SlavicPotato/ied-dev#57]
as detailed by this reddit post
https://www.reddit.com/r/skyrimmods/comments/13g1xok/weird_glow_around_character/

**Comment by SlavicPotato** [comment]
Light (enb light in particular) and/or glow meshes can still remain on torch displays with custom meshes.. These need to be handled explicitly by IED, if you attach a sample of the mesh I can take a look.
