### ISSUE TITLE
EditorID in the Form browser

### ISSUE THREAD

**Issue by Sant90JH** [SlavicPotato/ied-dev#59]
lots of neat statics and art objects etc. don't have a name but most do have a descriptive editor id to make browsing convenient
![Screenshot 2024-03-30 18-03-15](https://github.com/SlavicPotato/ied-dev/assets/50962437/4841eb4c-868f-4ec5-843f-fc06d9e05ec6)

**Comment by SlavicPotato** [comment]
True, but the game doesn't load them into memory for easy access (probably for memory conservation) and pulling it from bs files would be way too expensive.

**Comment by Sant90JH** [comment]
I see, that's unfortunate, thank you.
