### ISSUE TITLE
new styles only show if weapon is favorited but not equipped

### ISSUE THREAD

**Issue by dRAGONHEART8374** [SlavicPotato/ied-dev#61]
exactly as the title says. i have xpmsee installed but disabled in the mcm, i also have verolevi's all in one animations installed so i believe there's a conflict, but i'm not sure how to fix it

**Comment by SlavicPotato** [comment]
You're missing a dependency, see [https://www.nexusmods.com/skyrimspecialedition/mods/50049](https://www.nexusmods.com/skyrimspecialedition/mods/50049)
