### ISSUE TITLE
Unable to Hide Weapons

### ISSUE THREAD

**Issue by Schmuddie** [SlavicPotato/ied-dev#62]
![20240615124434_1](https://github.com/SlavicPotato/ied-dev/assets/172927844/654bf1e4-cfe3-4d75-bf8e-df0c2aa9c0c4)
Using Improved Camera SE, there is no option to hide weapons in IED as described.

**Comment by SlavicPotato** [comment]
Weapons can't be hidden per se, except for weapon _displays_. Gear nodes can be made invisible however, including any node that a weapon or weapon display _may_ attach to. Hiding a node makes all its children invisible.

So, you'll probably want to use the gear nodes view but note that I've no idea why you need to hide weapons or why IC is deferring to IED for this.
