### ISSUE TITLE
Crashlog referencing IED on Skyrim SE 1.6.1170

### ISSUE THREAD

**Issue by MarkoPabst** [SlavicPotato/ied-dev#64]
Random CTD that's happening quite frequently for me
Crashlog
https://pastebin.com/24q1fKbe
Modlist
https://pastebin.com/ty3ZKtky
Pluginlist
https://pastebin.com/8YaCgT08
Load order
https://pastebin.com/6Mzb27T9

**Comment by SlavicPotato** [comment]
Maybe something with AutoParallax, try disabling either plugin
