### ISSUE TITLE
Shield on back disappears when mounted, but re-appears if draw and sheath it while still mounted

### ISSUE THREAD

**Issue by SeaDaddytheRed** [SlavicPotato/ied-dev#65]
Hello, I have an issue where my shield visible on my back disappears when I mount my horse.  If I draw my weapon and shield then put them away the shield will appear on my back as normal.  Until I dismount and mount again and it will disappear again.

Spec.
Skyrim SE 1.6.1170 (Steam)
MO2 Load order:

<details><summary>Load Order</summary>
    <pre>
# This file was automatically generated by Mod Organizer.
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
ccASVSSE001-ALMSIVI.esm
ccBGSSSE001-Fish.esm
ccBGSSSE002-ExoticArrows.esl
ccBGSSSE003-Zombies.esl
ccBGSSSE004-RuinsEdge.esl
ccBGSSSE005-Goldbrand.esl
ccBGSSSE006-StendarsHammer.esl
ccBGSSSE007-Chrysamere.esl
ccBGSSSE010-PetDwarvenArmoredMudcrab.esl
ccBGSSSE011-HrsArmrElvn.esl
ccBGSSSE012-HrsArmrStl.esl
ccBGSSSE014-SpellPack01.esl
ccBGSSSE019-StaffofSheogorath.esl
ccBGSSSE020-GrayCowl.esl
ccBGSSSE021-LordsMail.esl
ccMTYSSE001-KnightsOfTheNine.esl
ccQDRSSE001-SurvivalMode.esl
ccTWBSSE001-PuzzleDungeon.esm
ccEEJSSE001-Hstead.esm
ccQDRSSE002-Firewood.esl
ccBGSSSE018-Shadowrend.esl
ccBGSSSE035-PetNHound.esl
ccFSVSSE001-Backpacks.esl
ccEEJSSE002-Tower.esl
ccEDHSSE001-NorJewel.esl
ccVSVSSE002-Pets.esl
ccBGSSSE037-Curios.esl
ccBGSSSE034-MntUni.esl
ccBGSSSE045-Hasedoki.esl
ccBGSSSE008-Wraithguard.esl
ccBGSSSE036-PetBWolf.esl
ccFFBSSE001-ImperialDragon.esl
ccMTYSSE002-VE.esl
ccBGSSSE043-CrossElv.esl
ccVSVSSE001-Winter.esl
ccEEJSSE003-Hollow.esl
ccBGSSSE016-Umbra.esm
ccBGSSSE031-AdvCyrus.esm
ccBGSSSE038-BowofShadows.esl
ccBGSSSE040-AdvObGobs.esl
ccBGSSSE050-BA_Daedric.esl
ccBGSSSE052-BA_Iron.esl
ccBGSSSE054-BA_Orcish.esl
ccBGSSSE058-BA_Steel.esl
ccBGSSSE059-BA_Dragonplate.esl
ccBGSSSE061-BA_Dwarven.esl
ccPEWSSE002-ArmsOfChaos.esl
ccBGSSSE041-NetchLeather.esl
ccEDHSSE002-SplKntSet.esl
ccBGSSSE064-BA_Elven.esl
ccBGSSSE063-BA_Ebony.esl
ccBGSSSE062-BA_DwarvenMail.esl
ccBGSSSE060-BA_Dragonscale.esl
ccBGSSSE056-BA_Silver.esl
ccBGSSSE055-BA_OrcishScaled.esl
ccBGSSSE053-BA_Leather.esl
ccBGSSSE051-BA_DaedricMail.esl
ccBGSSSE057-BA_Stalhrim.esl
ccBGSSSE066-Staves.esl
ccBGSSSE067-DaedInv.esm
ccBGSSSE068-Bloodfall.esl
ccBGSSSE069-Contest.esl
ccVSVSSE003-NecroArts.esl
ccVSVSSE004-BeAFarmer.esl
ccBGSSSE025-AdvDSGS.esm
ccFFBSSE002-CrossbowPack.esl
ccBGSSSE013-Dawnfang.esl
ccRMSSSE001-NecroHouse.esl
ccEDHSSE003-Redguard.esl
ccEEJSSE004-Hall.esl
ccEEJSSE005-Cave.esm
ccKRTSSE001_Altar.esl
ccCBHSSE001-Gaunt.esl
ccAFDSSE001-DweSanctuary.esm
_ResourcePack.esl
Occ_Skyrim_Tamriel.esp
Occ_Skyrim_AnnEdition.esp
unofficial skyrim special edition patch.esp
Unofficial Skyrim Modders Patch.esp
Vanilla Script MicroOptimizations.esl
Unique Flowers & Plants.esp
unofficial skyrim creation club content patch.esl
Improved Mountain LOD and Z Fight Patch.esp
Cathedral - 3D Mountain Flowers.esp
DwemerGatesNoRelock.esl
ABS-arrowsBoltsSink-1.0.esl
UHDAP - MusicHQ.esp
UHDAP - en0.esp
UHDAP - en1.esp
UHDAP - en2.esp
UHDAP - en3.esp
UHDAP - en4.esp
NoSillyPhysicsDamage.esl
RU_CityTreesSE_Markarth.esl
RU_CityTreesSE_Riften.esl
RU_CityTreesSE_Solitude.esl
RU_CityTreesSE_Whiterun.esl
PraedysSkeletons.esl
SurvivalControlPanel.esp
SmoothCam.esl
TrueHUD.esl
AHZmoreHUDInventory.esl
RU_CityTreesSE_Whiterun_RapidRock.esl
RU_CityTreesSE_Windhelm.esl
Enhanced Landscapes.esp
RU_CityTreesSE_Dawnstar.esl
RU_CityTreesSE_Karthwasten.esl
RU_CityTreesSE_Rorikstead.esl
RU_CityTreesSE_Rorikstead_Addon.esl
RU_CityTreesSE_Ivarstead.esl
RU_CityTreesSE_DragonBridge.esl
RU_CityTreesSE_WhiterunLanterns.esl
RU_CityTreesSE_Riverwood.esl
RU_CityTreesSE_Falkreath.esl
RU_CityTreesSE_RavenRock.esl
RU_CityTreesSE_Morthal.esl
RU_CityTreesSE_Whiterun_Addon3.esl
RU_CityTreesSE_BattleBorn.esl
RU_CityTreesSE_Chillfurrow.esl
RU_CityTreesSE_LoreiusFarm.esl
RU_CityTreesSE_Pelagia.esl
RU_CityTreesSE_SarethiFarm.esl
RU_CityTreesSE_SalviusFarm.esl
RU_CityTreesSE_Kynesgrove.esl
DynamicCollisionAdjustment.esl
BetterAnimals.esl
iWant Widgets.esl
wraithguardvaultfixer.esp
1NGarmor.esl
1FlutedArmor.esl
Skyrim Extended Cut - Saints and Seducers.esp
Tamrielic Distribution.esp
AHZmoreHUD.esl
Experience.esl
Silver Smelting.esl
FYX - Windhelm Graveyard.esp
RU_CityTreesSE_WhiterunOutskirt.esl
1NamelessSaber.esl
RU_CityTreesSE_Markarth_Addon3.esl
RU_CityTreesSE_Whiterun_Addon5.esl
RU_CityTreesSE_Apiaries.esl
RU_CityTreesSE_BrandyMugFarm.esl
RU_CityTreesSE_HollyFrostFarm.esl
Sentinel - Distribution Framework.esp
1FS.esl
Better Windhelm Ground Meshes Placement Corrections.esp
DynDOLOD.esm
EVGAnimatedTraversal.esl
MajesticMountains_Landscape.esm
SLSR - LargeRefs.esm
1FalconerArmor.esl
1SilverArmor.esl
1WR.esl
VLC - References.esm
1Dwemer.esl
FarmhouseChimneys.esp
JK's Markarth Outskirts.esp
MagicalCollegeofWinterhold.esp
JK's Riften Outskirts.esp
1FlutedArmor - Lydia Outfit by Xtudo.esp
JK's Windhelm's Outskirts.esp
JK's Whiterun's Outskirts.esp
JK's Solitude Outskirts.esp
Nature of the Wild Lands.esp
Cathedral Landscapes.esp
Mundus.esp
Aetherius.esp
Pilgrim.esp
Arena.esp
Skyrim is Cold - SPID.esp
MagicalBlackreach.esp
Inigo.esp
Rest By Campfire.esp
Silver Sword Merchants.esp
Skyrim Revamped Combat Boundaries Restored.esp
Silver Merchants Revamped Patch.esp
ShowPlayerInMenus.esp
ForswornRetexture Unique Armor of the Old Gods.esp
Enhanced Landscapes USSEP Patch.esp
Fish Plaque Retroactive Fix.esp
Trivial Smelters Solitude.esp
Trivial Smelters Riverwood.esp
Trivial Smelters Riften.esp
Book Covers Skyrim Updated.esp
Book Covers Skyrim Updated0.esp
Book Covers Skyrim Updated1.esp
Book Covers Skyrim - Lost Library.esp
pick_your_poison.esp
Sidequests of Skyrim.esp
geometric_stat_growth.esp
Blowing in the Wind SSE.esp
JorrvaskrKitchenSE.esp
dD - Enhanced Blood Main LITE.esp
LCO_Framework.esp
TacticalValtheim.esp
Item organizer.esp
SkyUI_SE.esp
SkyrimImprovedPuddles-DG-HF-DB.esp
Skyrim On Skooma.esp
SMIM-SE-Merged-All.esp
Ducks and Swans.esp
el_gildeddoubletsetcolor.esp
LunarGuardArmor.esp
LunarGuardArsenal_Battleaxe.esp
Kad_MoonMonkRobes.esp
Apex_Khajiit.esp
KhajiitHazWears.esp
Rumble - Beasts.esp
Rumble - Crafting.esp
Rumble - Items.esp
Rumble - Jumping.esp
Rumble - Swimming.esp
Rumble - UI.esp
Rumble - Weapons.esp
Audio Overhaul Skyrim.esp
Completionist.esp
Immersive Sounds - Compendium.esp
Rumble - Weapons - ISC.esp
Rumble - UI - ISC Patch.esp
Rumble - Jumping - ISC Patch.esp
Rumble - Items - ISC Patch.esp
Rumble - Crafting - ISC Patch.esp
ISC USSEP Patch.esp
Rumble - Crafting - AOS Patch.esp
Rumble - Jumping - AOS Patch.esp
Rumble - Swimming - AOS Patch.esp
Rumble - Weapons - AOS Patch.esp
AOS_ISC_Integration.esp
Regional Sounds Expansion.esp
Reverb Interior Sounds Expansion.esp
Reverb Interior Sounds Expansion_VolumeSlider_Rain.esp
Reverb Interior Sounds Expansion_VolumeSlider_Thunder.esp
Thaumaturgy.esp
BetterSpellCostStacking.esp
RelightingSkyrim_SSE.esp
DLBurningDriftWoodNotWLPatch.esp
DLSmoulderingPineTreesNotWLPatch.esp
SurvivalModeImproved.esp
Shadows Of Sunlight - In Small Exterior World Spaces.esp
Castle Volkihar Rebuilt.esp
aMidianBorn_Buildings Landscapes.esp
Rudy Nordic Pottery SSE.esp
BlendedRoadsFixes.esp
Stones of Solitude.esp
Sleeping Expanded.esp
Use Those Blankets.esp
The Heart Of Dibella - Quest Expansion.esp
Immersive Death Cycle.esp
The Whispering Door - Quest Expansion.esp
Nature of the Wild Lands - Autumn Birches.esp
NPCs React To Invisibility.esp
HouseOfHorrorsQuestExpansion.esp
SunAffectsNPCVampires.esp
SunAffectsNPCVampires-Hooded.esp
Caught Red Handed - Quest Expansion.esp
TheOnlyCureQuestExpansion.esp
Infiltration - Quest Expansion.esp
Simple Offence Suppression MCM.esp
RUSTIC SOULGEMS - Unsorted.esp
beltfastenedquivers.esp
GDOS - Splendid Mechanized Dwemer Door.esp
Footprints.esp
Cloaks of Skyrim.esp
Cathedral Weathers.esp
SBtNBE.esp
QuickLootEE.esp
Incognito.esp
AI Overhaul.esp
Cutting Room Floor.esp
Occ_Skyrim_CuttinRoomFloor.esp
Occ_Skyrim - JK Solitude Outskirts patch.esp
Occ_Skyrim_Jk's-Whiterun-Outskirts_patch.esp
Occ_Skyrim_JK's-Markarth-Outskirts_patch.esp
Occ_Skyrim_Patch_for_tree_replacers.esp
Better Animals - Cutting Room Floor.esp
MysticismMagic.esp
Adamant.esp
HandtoHand.esp
NoRoadPredatorsRedone.esp
Locked Chests Have Keys.esp
Remove Hanging Moss From Trees.esp
OpulentThievesGuild.esp
LCO_BannermistTower.esp
LCO_BleakFallsTower.esp
LCO_BleakwindBluff.esp
LCO_BthalftRuins.esp
LCO_CradleStoneTower.esp
LCO_DragonBridgeOverlook.esp
LCO_FalkreathWatchtower.esp
LCO_FourSkullLookout.esp
LCO_FSL-KotN_Patch.esp
LCO_LostValleyRedoubt.esp
LCO_MarasEyeDen.esp
LCO_MolderingRuin.esp
LCO_Nilheim.esp
LCO_PinefallBridge.esp
LCO_PinemoonCave.esp
LCO_RedwaterDen.esp
LCO_RiftWatchtower.esp
LCO_ShorsWatchtower.esp
LCO_SnowpointBeacon.esp
LCO_StendarrsBeacon.esp
BetterQuestObjectives.esp
Allied Arvak.esp
BetterQuestObjectives-CRFPatch.esp
BetterQuestObjectives-DBForevertoMisc.esp
Ash Pile Expiration.esp
Fullscreen Book and Item Zoom.esp
Move it Dammit - Less Wait Time.esp
sandboxcylinderheight.esp
PeopleAreStrangers.esp
TimingIsEverything.esp
lessrandomencounters10.esp
SimplyOverflowingSalt.esp
ThugsNotAssassins.esp
Eli_Dovah Vault.esp
Eli_CLBladeOfWoePatch.esp
AOS_EBT LITE Patch.esp
I4IconAddon.esp
RadiantRequirements.esp
ThugsNotAssassins_TIE.esp
Thugs Not Assasins - BCSU Patch.esp
Cathedral Weather Godrays.esp
SkyHUD.esp
QuickLight.esp
The Whispering Door QE - USSEP Patch.esp
hideQuestItems.esp
ISC Mysticism Patch.esp
SeranaAnimationDisabler.esp
Apothecary.esp
Creation Club Integration - Anniversary Edition.esp
Guard Dialogue Overhaul.esp
Must be my imagination.esp
Hunters Not Bandits.esp
HNB - MBMI Patch.esp
Embers XD.esp
Embers XD - Patch - Goldenhills Plantation.esp
Crime Overhaul.esp
Take All Loose Gold and Arrows.esp
CrimeDecay.esp
FlickeringShadowsFix.esp
Smoking Torches And Candles.esp
HPP - Vaermina's Torpor.esp
WerewolfTransformationTimer.esp
know_your_enemy_2_armors.esp
know_your_enemy2.esp
know_your_enemy_2_integration_patch.esp
Manbeast.esp
CC Farming - Tweaks and Enhancements.esp
hearthfireextended.esp
Point The Way.esp
Scheduling of Sleep.esp
Thieves Guild Requirements.esp
Scion.esp
Pheasants.esp
SSoB.esp
CRF - Lighting Overhaul.esp
SeagullsofSkyrim.esp
OpulentThievesGuildPatch.esp
BetterAnimals_Addon1.esp
MenuMaid2.esp
NightEyeToggle.esp
Afterlife.esp
TheChoiceIsYours.esp
TCIY_CRF_Patch.esp
CC-Saints&Seducers_TCIY_Patch.esp
Carriage Drivers Are Alive.esp
WIZ_FoscsF.esp
FlyingCrowsSSE.esp
Dlizzio's Mesh Fixes.esp
mihailseal.esp
mihailguar.esp
mihailpigeon.esp
man_DaedricShrines.esp
man_DaedricShrines - The Only Cure patch by Xtudo.esp
MCoW_RelightingSkyrim.esp
Ivy Replacer BOS.esp
Cutting Room Floor - BCSU Patch.esp
AI Overhaul - Cutting Room Floor Patch.esp
MCoW_Cutting Room Floor.esp
man_dibella.esp
man_kynarethStatue.esp
man_maraStatue.esp
man_sithis.esp
Bells of Skyrim.esp
SkyrimReputation_SSE.esp
mihailseacow.esp
mihailbeakedsauroids.esp
PaarthurnaxQuestExpansion.esp
GDOS - Glorious Solitude Door - Rotation Fix.esp
mihailmountainlion.esp
PilgrimsDelight.esp
Opulent Thieves Guild - Embers XD [XD ESP] Patch.esp
Opulent Thieves Guild - USSEP Patch.esp
HoldBorderBanners.esp
CarriageStationsTowns.esp
Stormcrown.esp
Destroy the Dark Brotherhood - Quest Expansion.esp
CoW Entry Requirements.esp
Innocence Lost - Quest Expansion.esp
College Of Winterhold - Quest Expansion.esp
DeadlySpellImpacts.esp
DeadlySpellImpacts - AOS + ISC.esp
DSI AOS ISC Patch.esp
GIST soul trap.esp
GIST-RusticSoulGems-patch.esp
CompanionsProgressionRequirements.esp
SimpleTaxes.esp
UIExtensions.esp
Improved Traps.esp
Opulent Thieves Guild - FPS Fix.esp
Rally's Nord War Horns - Unique Torygg's Horn.esp
Embers XD - Fire Magick Add-On.esp
Apothecary - BCSU Patch.esp
DestructibleDisplayCases.esp
JS Barenziah SE - Johnskyrim.esp
JS Instruments of Skyrim SE - Uniques.esp
JS Emissive Eyes SE - Johnskyrim.esp
Better Animals - Emissive Eyes Patch.esp
Manbeast - Emissive Eyes Patch.esp
DeadlySpellImpacts - Mysticism.esp
mihailpigeon - smaller pigeons.esp
RadiantRequirements - Mysticism.esp
TheChoiceIsYours - Lod Dialogue Tweak.esp
The Choice is Yours - BCSU Patch.esp
fixLOD.esp
Dynamic Things Alternative.esp
RealRabbitsHD.esp
DynamicAnimalVariantsPlus.esp
House Requirements - Bloodchill Manor.esp
House Requirements - Gallows Hall.esp
House Requirements - Hendraheim.esp
House Requirements - Shadowfoot Sanctum.esp
House Requirements - Tundra Homestead.esp
Realistic AI Detection 3 - Medium Interior, Medium Exterior.esp
Camping Expansion.esp
CT_AskToShowRoom.esp
Don'tTalkWithYourMouthFull.esp
Crime Overhaul - CRF Patch.esp
HFE-CRF-Patch.esp
Simplicity of Snow.esp
Scared of Shootings.esp
BetterQuestObjectives-PaarExpansion Patch.esp
MCMHelper.esp
Player Spell Lighting.esp
Player Spell Lighting - Mysticism.esp
PassiveWeaponEnchantmentRecharging.esp
Precision.esp
CathedralWeatherMCM.esp
MoonsAndStars.esp
WadeInWater.esp
WadeInWaterRedone.esp
Simple Degradation.esp
CraftableUpgradeableSilver.esp
Repair Kit.esp
RemoveIncreasedtoTextAndSound.esp
Dragon Combat Overhaul.esp
TrueDirectionalMovement.esp
Whiterun Tower - Mesh Fix.esp
Simplicity of Snow - Dwemer Sanctuary Patch.esp
Camping Extended.esp
Road Signs Fast Travel.esp
Bounty Gold.esp
Journeyman.esp
Gourmet.esp
GourmetTables.esp
Candlehearth.esp
challenging_spell_learning.esp
RAEQuestRequirements.esp
AutoShowNote.esp
House Requirements - Bloodchill Manor RAE Patch.esp
Misc Dialogue Edits.esp
radiantBlocker.esp
More Dialogue Options.esp
More Dialogue Options - Guard Dialogue Overhaul patch.esp
Modern Brawl Bug Fix.esp
ALT - Crates - BOS.esp
Keytrace.esp
sweepingOrganizesStuff.esp
ShovelBody.esp
Edryu Widget.esp
Even Better Quest Objectives - BCSU Patch.esp
BetterThirdPersonSelection.esp
Animals Swim.esp
SensibleBribes.esp
SimplestHorses.esp
BlockStealPapyrus.esp
AmbientBirdsExpanded.esp
BetterAnimals_SHAOMPatch.esp
Cloaks of Skyrim - Thaumaturgy.esp
WaitYourTurn.esp
Quick Follower Commands.esp
Luminosity Lighting Overhaul.esp
MCoW_Luminosity.esp
Blowing in the Wind Lite.esp
Silver Arrows.esp
Simplicity of Seeding.esp
RainExtinguishesFires.esp
SkyrimMovementControl.esp
sick_comments_begone.esp
Belethor's Sister.esp
PhotoMode.esp
Imperial Armors and Weapons Retexture SE - Penitus Pants.esp
Imperial Armors and Weapons Retexture SE - Falx Carius.esp
Artificer.esp
Artificer - Dragon Priest Staves.esp
Artificer - USSEP.esp
Artificer - Xavbio Old Gods.esp
ArtificerXav.esp
DragonPriestArmor.esp
Tamrielic Distribution - AA Ebony Plate.esp
Tamrielic Distribution - AA Elven Hunter.esp
Tamrielic Distribution - AA Iron.esp
Tamrielic Distribution - AA Leather.esp
Tamrielic Distribution - AA Silver.esp
Tamrielic Distribution - AA Steel Soldier.esp
Tamrielic Distribution - Crossbow Collection.esp
Tamrielic Distribution - Dead Man's Dread.esp
Tamrielic Distribution - Netch Leather Armor.esp
Tamrielic Distribution - Rare Curios.esp
Tamrielic Distribution - Vigil Enforcer Armor.esp
Tamrielic Distribution - Moon Monk Robes and Lunar Guard Armor.esp
Crossbow Integration.esp
Crossbow Integration - Elite Crossbows.esp
Crossbow Integration - Expanded Crossbow Pack.esp
Crossbow Integration - Expanded Crossbow Pack Orcish Extension CRF.esp
Crossbow Integration - Rare Curios Bolts.esp
Silver Arrows - Crossbow Integration - Tamerialic Distribution Patch.esp
Silver Arrows Skyrim Revamped Patch.esp
Gourmet - AI Overhaul.esp
Gourmet - beafarmer.esp
Gourmet - Bittercup.esp
Gourmet - bowofshadows.esp
Gourmet - petnhound.esp
Gourmet - puzzledungeon.esp
GourmetECSS.esp
GourmetFishing.esp
GourmetSurvival.esp
GourmetUSSEP.esp
Sentinel.esp
1SilverArmor.esp
KYE2 Silver Arrows Patch.esp
UniqueDragonPriests_XB.esp
ECSS - Book Covers Skyrim Patch.esp
ECSS - Ruin's Edge Patch.esp
ECSS - Shadowrend Patch.esp
ECSS - Staff of Sheogorath Patch.esp
Sentinel - Imperial Crafting.esp
1YsmirArmorSE.esp
1Dwemer.esp
1FlutedArmor.esp
Sentinel + CC Armors.esp
Sentinel + CC Backpacks.esp
Sentinel + CC Ghosts of the Tribunal.esp
Sentinel + CC Netch Leather.esp
Sentinel - USSEP Patch.esp
BlendedRoads.esp
Experience Quests Tweak.esp
The Cause - EL Patch.esp
Ruin Coins.esp
Clear Shaders.esp
Diverse Campfires BOS.esp
StaticSkillLeveling.esp
Ruin Coins - The Cause.esp
Ruin Coin - Adamant.esp
Ruins Coins - Less Valuable.esp
Ruin Coins - Saints and Seducers Extended Cut.esp
Ruin Coins - Drakr Variations.esp
Lawbringer Bounty Gold Patch.esp
Skyrim Extended Cut - Saints and Seducers Open Helmet Patch.esp
Crossbow Integration - Complete No WACCF.esp
Creation Club Integration - Anniversary Edition No WACCF.esp
Dynamic Activation Key.esp
Grass Patch - All CC Mods.esp
Landscape Fixes For Grass Mods.esp
Vanilla Landscape Corrections.esp
Complementary Grass Fixes.esp
Complementary Grass Fixes - CRF Patch.esp
LightBodyHorsesReplacer.esp
Press E To Heal Followers.esp
Eli_InigoBloodchillPatch.esp
Enhanced Landscapes Inigo Patch.esp
Enhanced Landscapes - AE Patch.esp
HouseOfHorrorsQuestExpansion - TheChoiceIsYours.esp
SimplerKnock.esp
CC Experience - USCCCP patch.esp
CC Experience - ECSS  - Patch.esp
CCQuest - Experience Patch.esp
CC Open Helmets Merged.esp
CC Open Helmets Merged USCCCP.esp
CC Open Helmets Merged CCI AE.esp
CC-Bittercup_TCIY_Patch.esp
CC-BloodchillManor_TCIY_Patch.esp
CC-HeadmansCleaver_TCIY_Patch.esp
CC-Hendraheim_TCIY_Patch.esp
CC-PlagueOfTheDead_TCIY_Patch.esp
CC-StaffOfSheogorath_TCIY_Patch.esp
CC-Sunder&Wraithguard_TCIY_Patch.esp
CC-VigilEnforcer_TCIY_Patch.esp
BowOfShadowsFix.esp
NPCSpdDiv.esp
Simple Fishing Overhaul.esp
SkaldsMail.esp
Fish Anywhere.esp
Apothecary - Rare Curios Patch.esp
Apothecary - Fishing Patch.esp
Apothecary - Saints & Seducers Patch.esp
BlackreachEerieAmbience.esp
AcousticTemplateFixes.esp
AcousticTemplateFixes_CC_Farming.esp
AcousticTemplateFixes_Luminosity.esp
AcousticTemplateFixes_CC_Seducers_EC.esp
AcousticTemplateFixes_ReverbInteriorSounds.esp
BladeAndBlunt.esp
BBNoKillmoves.esp
NPCs Take Cover.esp
BBVanillaSliders.esp
Starfrost.esp
Better Harvesting.esp
StarfrostSpells.esp
Scarecrows_of_Skyrim.esp
Saints and Seducers Tweaks Open Helmet EC.esp
Sentinel - Unique Guard Meshes.esp
Sentinel - Unique Skyforge Meshes.esp
Sentinel - Unique Stormcloak Meshes.esp
1FS.esp
1Markynaz.esp
JKs Windhelm Outskirts - Scarecrows of Skyrim patch.esp
JKs Windhelm Outskirts - CC Ebony Plate Armor patch.esp
JKs Windhelm Outskirts - CDAA patch.esp
JKs Windhelm Outskirts - Enhanced Landscapes patch.esp
JKs Windhelm Outskirts - Farmhouse Chimneys patch.esp
JKs Windhelm Outskirts - USSEP patch.esp
Solitude Braziers.esp
Innocence Lost QE - USSEP Patch.esp
HonedMetal.esp
Icy Windhelm.esp
AretinoHome.esp
DapperDeliveries_CourierOverhaul.esp
Vanilla Eating Animation Fix.esp
Nordic Faces - WoodElfFemale Fix.esp
Nordic Faces - FaceGeom.esp
Nordic Faces - FaceTint.esp
Nordic Faces - FaceTint0.esp
CT_10_AllInOne_A1.esp
CT_10_WhiterunOutskirt_A1.esp
CT_70_Rorikstead_NOTWL_PATCH.esp
CT_90_Whiterun_LessTrees_PATCH.esp
CT_70_BattleBorn_JKsWO_PATCH.esp
CT_70_Chillfurrow_CityTreesWO_PATCH.esp
CT_70_Chillfurrow_CuttingRoomFloor_PATCH.esp
CT_70_Chillfurrow_eFPS_PATCH.esp
CT_70_LoreiusFarm_LFFGM_PATCH.esp
CT_70_Pelagia_eFPS_PATCH.esp
CT_70_Pelagia_JKsWO_PATCH.esp
CT_70_SarethiFarm_LFFGM_PATCH.esp
CT_70_SalviusFarm_EnhancedLandscapes_PATCH.esp
CT_70_WhiterunOutskirt_JKsWO_PATCH.esp
JKs Riften Outskirts - AI Overhaul patch.esp
JKs Riften Outskirts - Carriage Drivers Are Alive patch.esp
JKs Riften Outskirts - CC Wild Horses patch.esp
JKs Riften Outskirts - Enhanced Landscapes patch.esp
JKs Riften Outskirts - Scarecrows of Skyrim patch.esp
JKs Whiterun Outskirts - USSEP Patch.esp
JKs Whiterun Outskirts - Enhanced Landscapes patch.esp
JKs Whiterun Outskirts - CC Fishing patch.esp
JKs Whiterun Outskirts - Hearthfire Extended Patch.esp
JKs Whiterun Outskirts - Landscape Fixes for Grass Mods patch.esp
JKs Whiterun Outskirts - Nature of the Wild Lands patch.esp
JKs Whiterun Outskirts - Tundra Homestead Patch.esp
JKs Markarth Outskirts - CC Fishing patch.esp
JKs Markarth Outskirts - CDAA patch.esp
JKs Markarth Outskirts - Enhanced Landscapes patch.esp
Sentinel - Adamant Patch.esp
Dragonborns Bestiary.esp
Ascend - Hidden Peaks of Skyrim.esp
RainExtinguishesEmbersXD.esp
footprints-ultimateFix.esp
evgCLAMBER.esp
AutoLockpicking.esp
JunkIt.esp
UntarnishedUI_Blur.esp
UntarnishedUI_Subtitle.esp
Snowy Landscapes in Snowy Regions.esp
SLSR - Cutting Room Floor Patch.esp
FSMPM - The FSMP MCM.esp
VLC Patch - CuttingRoomFloor.esp
Innocence Lost - Aretino Residence Patch.esp
DragonPriestArmorArtificer.esp
Cathedral Dynamic Snow.esp
Embers XD - Patch - Survival Mode Improved.esp
NotWL - Better Harvesting.esp
Static Objects Swap - Unique Wooden Bridges.esp
AdamantSmithing.esp
SimonrmSaintsSeducersSmithing.esp
SimonrimAttackSpeedFix.esp
MundusUSSEP.esp
AetheriusSpells.esp
StarfrostInjuries.esp
HandToHandLocksmith.esp
H2HBooksandTrainers.esp
Lockpicks Aint Bobby Pins.esp
AlternatePerspective.esp
Misc Dialogue Edits - Alternate Perspective Patch.esp
Alternate Perspective - Gate to Sovngarde Edition.esp
DynDOLOD.esp
Occlusion.esp
SkyValor.esp
Synthesis.esp
water mod.esp
FWMF for Fantasy Paper Maps.esp
MCM for FWMF.esp
Dayspring Canyon Paper Map for FWMF.esp
Forgotten Vale Map for FWMF.esp
Markarth Paper Map for FWMF.esp
Soul Cairn Paper Map for FWMF.esp
Sovngarde Paper Map for FWMF.esp
Blackreach Paper Map for FWMF.esp
 </pre>
   </details>

**Comment by SlavicPotato** [comment]
It's vanilla functionality that affects equpped shields, it's supposed to hide them when mounted, assuming the shield is in your arm.

This mod doesn't handle that, take a look in SimpleDualSheath.ini, ```DisableHideOnSit``` option.

**Comment by SeaDaddytheRed** [comment]
Thank you for the quick response.  Setting the Player and NPC flags in the ini did the trick.
