### ISSUE TITLE
CTD after updating to newest Version (Ver. 1.4.0)

### ISSUE THREAD

**Issue by Saphira2812** [SlavicPotato/ied-dev#7]
I think something broke/corrupted about NPCs Bows in the new Update? I always CTD at Hillgrunds Tomb now after I updated, didn't have any Issues with this and my Mods listed in the Crashlog before I updated. First I re-run Synthesis to see if it only needed to be regenerated for the IED Update but that wasn't it either.

This is what the Crashlog said: 

 AlchemyItem(Name: `Zaubertrank der Kleinen Heilung`, FormId: 0003EADD, File: `Skyrim.esm`)
  [   1]    TESNPC(Name: `Golldir`, FormId: 00019FE8, File: `NPC Appearances Merged.esp <- Unofficial Skyrim Special Edition Patch.esp <- Skyrim.esm`)
  [   1]    Character(FormId: 000A7360, File: `Skyrim.esm`, BaseForm: TESNPC(Name: `Golldir`, FormId: 00019FE8, File: `NPC Appearances Merged.esp <- Unofficial Skyrim Special Edition Patch.esp <- Skyrim.esm`))
  [  26]    BSFadeNode(Name: `skeleton.nif`, Owner: `Character(FormId: 000A7360, File: `Skyrim.esm`, BaseForm: TESNPC(Name: `Golldir`, FormId: 00019FE8, File: `NPC Appearances Merged.esp <- Unofficial Skyrim Special Edition Patch.esp <- Skyrim.esm`))`)
  [  34]    NiNode(Name: `WeaponBowIED`)
  [  35]    NiNode(Name: `WeaponBow`)
  [  39]    BSFlattenedBoneTree(Name: `NPC Root [Root]`)
  [ 111]    TESRace(Name: NordRace `Nord`, FormId: 00013746, File: `Synthesis.esp <- Update.esm <- Skyrim.esm`)
  [ 201]    NiCamera(Name: null)
}

Probable callstack
{
  [0]   0x7FF7946472DF     (SkyrimSE.exe+C072DF)          MutexRW::EnterReadLock_C072D0+F
  [1]   0x7FFF6E505710     (ImmersiveEquipmentDisplays.dll+A5710)

**Comment by SlavicPotato** [comment]
The relevant objects section in these crash logs is completely useless to me and you cut off the rest of it which may actually be useful (registers in particular).
