### ISSUE TITLE
X and Y rotation are correct but Z rotates with object

### ISSUE THREAD

**Issue by parsafaramarzi** [SlavicPotato/ied-dev#9]
this has been an issue since the first release but so far ive convinced myself that i was making a mistake and theres no issue with that but   finally i decided to report this here. the X axis is static and the object rotates correctly around it. Y axis also static  and the object rotates around it but the Z axis moves with the object when X or Y is changed. this creates sometimes frustrating situations. fixing this issue will probably mess everyone's settings up probably but i personally dont mind that at all i made all my presets myself i would just have to correct the rotations once more for myself.

**Comment by SlavicPotato** [comment]
I don't think there is one - those are euler angles, they're converted to a 3x3 matrix (https://github.com/ianpatt/skse64/blob/master/skse64/NiTypes.cpp#L185) and written directly to the node local transform (maybe the localspace coordinates are the source of confusion here?) (https://github.com/SlavicPotato/ied-dev/blob/master/ImmersiveEquipmentDisplays/IED/Controller/ObjectManagerCommon.h#L21, https://github.com/SlavicPotato/ied-dev/blob/master/ImmersiveEquipmentDisplays/IED/Controller/INode.cpp#L27). If you can find an issue with the euler to matrix conversion (other than "i think it's wrong" or "i think it's inconvenient") be sure to let me know. Beyond that it's completely up to the engine, the worldspace calculations (ie where the object actually ends up) are done by the game, not the plugin.

**Comment by parsafaramarzi** [comment]
hmm cant help more regarding this issue because i barely understand whats happening if it isnt X Y Z tbh .but havent you noticed anything weird with the rotation yourself? i think after tweaking and messing with the rotation you should be able to understand what im talking about. other than that idk ill go mess around with it again. there really might be something wrong with the conversion

**Comment by SlavicPotato** [comment]
> hmm cant help more regarding this issue because i barely understand whats happening

And that's a problem, you're claiming an issue but apparently don't have even a basic understanding how orientation is represented in euler angles. No doubt there's additional confusion from the fact that rotations are done in localspace (relative to the parent node) and the fact that an object may or may not be centered on the node you're manipulating (weapons certainly aren't). 

No, I've not noticed anything out of the ordinary, skse euler functions seem fine. Considering some major projects use them (skee/racemenu for one) , someone would probably have caught on by now.

This visualizer may help to imagine it: https://compsci290-s2016.github.io/CoursePage/Materials/EulerAnglesViz/

**Comment by SlavicPotato** [comment]
Bit more info regarding euler angles, I didn't have time to write this earlier:

There are many different conventions for rotation axes (24 total) which define the axes and order in which the rotations are applied.  I won't go into too much detail (you can read more on [wikipedia](https://en.wikipedia.org/wiki/Euler_angles#Chained_rotations_equivalence)), I'll just explain about intrinsic (mobile) and extrinsic (fixed frame) rotations:

With intrinsic rotations the first axis is fixed and each subsequent axis in the sequence is rotated around the basis of the new frame, for example an x->y'->z' convention would first apply the angle around x, then y relative to the previous result and finally z, again relative to the previous result (xy).

Extrinsic (fixed) are applied relative to fixed XYZ coordinates on each axis, there's no rotation relative to the last result in the sequence.

For example, the visualizer linked above uses intrinsic α->β'->γ' convention, when moving yaw you'll notice it's fixed, then each next slider rotates relative to preceding result. 

SetEulerAngles which IED uses is intrinsic, sequence y->z'->x'. I'm guessing this is what's tripped you up into thinking it's a bug. Your OP is not exactly correct, only rotations around the first (y) axis are fixed, z is relative to y and x relative to zy. These represent yaw, pitch and roll.

So I suppose the question is, should extrinsic rotations be implemented as an optional.
